Scrapper:
  URL: https://www.hellofresh.be/about/nieuws?locale=fr-BE
WebDAV:
  URL: http://localhost:8080/remote.php/dav/files/admin/
  Username: admin
  Password: secret
  Folder: /Documents/à trier
  FolderFormat: "2006"
