volumes:
  db:
  nextcloud:
  vsftpd:

services:
  db:
    image: docker.io/library/mariadb:10.5
    expose:
    - "3306"
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=nextcloud
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

  # URL: http://localhost:8080/apps/dashboard/
  nextcloud:
    image: docker.io/library/nextcloud:23-fpm-alpine
    restart: always
    expose:
      - "9000"
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=secret
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost

  nginx:
    image: docker.io/library/nginx:1.23-alpine
    restart: always
    ports:
    - "8080:8080"
    links:
      - nextcloud
    volumes:
      - .podman-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - nextcloud:/var/www/html

  vsftpd:
    image: quay.io/itix/vsftpd:v0.0.22
    restart: always
    ports:
    - "2121:2121"
    - "30100-30119:30100-30119"
    volumes:
      - .podman-compose/vsftpd/config:/etc/vsftpd:z
      - .podman-compose/vsftpd/users:/etc/vsftpd-users:z
      - vsftpd:/srv/vsftpd
